In [5]:
print("20242077")
print("정재혁")

20242077
정재혁


In [6]:
#예제1
symbols = "$*&!@"
codes = []

for symbol in symbols :
  codes.append(ord(symbol))
print(codes)

[36, 42, 38, 33, 64]


In [7]:
#예제2
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]


In [9]:
#예제3
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [10]:
#예제4
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [13]:
#예제5
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord,symbols)))
print(beyond_ascii, "\n")
print(f"Map function:\n>>>{map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>><map object at 0x7cce46923d30>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [14]:
#예제6
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))


[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [15]:
#예제7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [16]:
#예제8
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
    print(tshirt)


black S
white S
black M
white M
black L
white L


In [17]:
#예제9
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [
    ('USA', '31195855'),
    ('BRA', 'CE342567'),
    ('ESP', 'XDA205856'),
]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [18]:
#예제10
for country, _ in traveler_ids :
  print(country)

USA
BRA
ESP


In [19]:
#예제11
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [20]:
#예제12
a = 10
b = 20
b, a = a, b
print(a, b)

20 10


In [21]:
#예제13
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)


(2, 4)
(2, 4)
2 4


In [22]:
#예제14
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)


idrsa.pub


In [23]:
#예제15
a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)

0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [24]:
#예제16
a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


In [25]:
#예제17
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46)),
]

print('{:15} | {:9} | {:9}'.format('name', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

name            | lat.      | long.    
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [26]:
#예제18
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))

print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


In [27]:
#예제19
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
LatLong = namedtuple('LatLong', 'lat long')

delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
print(delhi._asdict())

for key, value in delhi._asdict().items():
    print(key + ':', value)

{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [28]:
#예제20
l = [10, 20, 30, 40, 50, 60]
print(l[:2])     # [10, 20]
print(l[2:5])    # [30, 40, 50]
print(l[3:])     # [40, 50, 60]

[10, 20]
[30, 40, 50]
[40, 50, 60]


In [29]:
#예제21
invoice = """
0.....6........................25...........33..........40........
1909  Pimoroni PiBrella         $17.50      3           $52.50
1489  6mm Tactile Switch x20    $4.95       2           $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

       $ Pimoroni PiBrella  
x20    $ 6mm Tactile Switch 
 


In [30]:
#예제22
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3:2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 22, 30, 5, 8, 9]


In [31]:
#예제23
l = list(range(10))

In [32]:
#예제24
l = list(range(10))
l[2:5] = [100]
print(l)

[0, 1, 100, 5, 6, 7, 8, 9]


In [33]:
#예제25
l = [1, 2, 3]
print(l * 5)

print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


In [34]:
#예제26
board = [['_'] * 3 for i in range(3)]
print(board)

board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [35]:
#예제27
weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board[1][2] = '0'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]


In [36]:
#예제28
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'
print(board)

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]


In [37]:
#예제29
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

print(board)
board[2][0] = 'X'
print(board)


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]


In [38]:
#예제30
l = [1, 2, 3]
print(id(l))

l *= 2
print(l)
print(id(l))

137225379636992
[1, 2, 3, 1, 2, 3]
137225379636992


In [39]:
#예제31
t = (1, 2, 3)
print(id(t))

t *= 2
print(t)
print(id(t))

137226219904128
(1, 2, 3, 1, 2, 3)
137225375705760


In [40]:
#예제32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]   # TypeError 발생!
print(t)
"""
퀴즈 해설:
a. (1, 2, [30, 40, 50, 60]) 이 된다. ❌
b. 튜플 객체는 항목 할당을 지원하지 않는다 에러 발생. ⭕
c. a와 b 둘 다 틀리다. ❌
d. a와 b 둘 다 맞다. ❌
정답: b
"""


(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [41]:
#예제33
print(t)

(1, 2, [30, 40, 50, 60])


In [42]:
#예제34
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))
print(fruits)

print(sorted(fruits, reverse=True))
print(sorted(fruits, key=len))

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']


In [43]:
#예제35
print(sorted(fruits, key=len, reverse=True))
print(fruits)

fruits.sort()
print(fruits)

['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


In [44]:
#예제36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
print(floats[-1])

0.010678297958245375


In [45]:
#예제37
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')
with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

print(floats2[-1])
print(floats == floats2)

0.010678297958245375
True


In [46]:
#예제38
# 예제 38. 배열 항목 값의 바이트 중 하나 변경
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])   # 'h' = signed short (2바이트)
memv = memoryview(numbers)

print(len(memv))        # 5
print(memv[0])          # -2

memv_oct = memv.cast('B')   # 'B' = unsigned char (1바이트)
print(memv_oct.tolist())    # [254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

memv_oct[5] = 4
print(numbers)          # array('h', [-2, -1, 1024, 1, 2])

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [47]:
#예제 38-1
data = bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])      # 104 ('h'의 아스키코드 값)
mv[0] = 72        # 'h' → 'H' (원본 수정됨)

print(data)       # bytearray(b'Hello world')

104
bytearray(b'Hello world')


In [51]:
#예제39
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
type(a)

numpy.ndarray

In [53]:
#예제40
a.shape

(12,)

In [54]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
#예제41
a[2]

array([ 8,  9, 10, 11])

In [58]:
a[2, 1]

np.int64(9)

In [59]:
a[:, 1]

array([1, 5, 9])

In [60]:
#예제42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])